# dpcker compose with postgres install with pgvector extension

version: '3.8'

services:
  db:
    image: ankane/pgvector:latest 
    container_name: jarvis-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jarvis
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local